version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories: [/, /deploy/caddy]
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /deploy/caddy
    schedule:
      interval: weekly
