#!/bin/sh
set -eu

cd "$(dirname "$0")/.."
if [ "$#" -eq 0 ]; then
  set -- up --build --watch
fi

exec docker compose --env-file .env.example -p gradepush-development -f compose.development.yaml "$@"
